name: CI SNAPSHOT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-snapshot:
    uses: artembilan/spring-messaging-build-tools/spring-artifactory-gradle-snapshot.yml@main
    secrets: inherit