name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}

jobs:
  build_snapshot:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spring-projects'
    name: CI Build ${{ github.ref_name }} SNAPSHOT
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Configure JFrog Cli
        run: |
          jf rt gradlec \
            --use-wrapper \
            --uses-plugin \
            --deploy-ivy-desc=false \
            --server-id-resolve repo.spring.io \
            --server-id-deploy repo.spring.io \
            --repo-resolve snapshot \
            --repo-deploy snapshot
          echo JFROG_CLI_BUILD_NAME=spring-integration-aws-${{ github.ref_name }} >> $GITHUB_ENV
          echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV
      - name: Build and Publish
        run: |
          jf rt gradle build dist artifactoryPublish
#          jf rt build-publish