name: Close Milestone and Notify Slack

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'The tag of the release for Milestone to close. Usually starts with `v`'
        required: true
        type: string
  workflow_call:
    inputs:
      releaseTag:
        description: 'The tag of the release for Milestone to close. Usually starts with `v`'
        required: true
        type: string

jobs:
  close-milestone:

    runs-on: ubuntu-latest

    steps:

      - name: Close Milestone
        id: milestone-id
        run: |
          TAG=${{ inputs.releaseTag }}
          export MILESTONE_NAME=${TAG#v}
          MILESTONE_ID=$(gh api repos/$OWNER/$REPO/milestones --jq '.[] | select(.title == env.MILESTONE_NAME) | .number')
          if [ $MILESTONE_ID ]; then
            gh api -X PATCH repos/$OWNER/$REPO/milestones/$MILESTONE_ID -f state='closed' --silent
          fi
          echo version=$MILESTONE_NAME >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

#      - name: Announce Release on Slack
#        uses: slackapi/slack-github-action@v1.24.0
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_SLACK_WEBHOOK_URL }}
#          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
#        with:
#          payload: |
#            {
#              "text": "${{ github.event.repository.name }}-announcing `${{ steps.milestone-id.outputs.version }}`"
#            }
