name: Promote Staged GA to Central

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
      buildNumber:
        description: 'The Artifactory Build'
        required: true

jobs:
  release_to_central:
    uses: .github/workflows/spring-artifactory-promote-central.yml
    with:
      buildName: ${{ inputs.buildName }}
      buildNumber: ${{ inputs.buildNumber }}
    secrets: inherit