name: Promote Staged GA to Central

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: 'The Artifactory Build Name'
        required: true
      buildNumber:
        description: 'The Artifactory Build Number'
        required: true

jobs:
  release_to_central:
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-artifactory-promote-central.yml@main
    with:
      buildName: ${{ inputs.buildName }}
      buildNumber: ${{ inputs.buildNumber }}
    secrets: inherit