name: Release

on:
  workflow_dispatch:

run-name: Release current version for branch ${{ github.ref_name }}

jobs:
  release:
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-artifactory-release.yml@main
    with:
      buildToolArgs: dist
    secrets: inherit