name: Build and Stage Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
      nextDevelopmentVersion:
        description: 'Next development version like 3.1.1-SNAPSHOT'
        required: true

jobs:
  staging:
    uses: ./.github/workflows/spring-artifactory-gradle-release-staging.yml
    with:
      releaseVersion: ${{ inputs.releaseVersion }}
      nextDevelopmentVersion: ${{ inputs.nextDevelopmentVersion }}
    secrets: inherit