name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string

jobs:
  release:
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-artifactory-release.yml@main
    with:
      releaseVersion: ${{ inputs.releaseVersion }}
      buildToolArgs: dist
      repositoryTeam: artembilan,garyrussell
    secrets: inherit