name: Stage Release with Gradle to Artifactory

on:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string

jobs:
  staging-with-gradle:
    uses: spring-projects/spring-integration-aws/.github/workflows/spring-artifactory-gradle-release-staging.yml@main
    with:
      releaseVersion: ${{ inputs.releaseVersion }}
    secrets: inherit