name: Verify

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version like 3.0.0-M1, 3.1.0-RC1, 3.2.0 etc.'
        required: true
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

      - name: Invoke verification workflow
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: verify-staged-artifacts.yml
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
          inputs: '{ "releaseVersion": "${{ inputs.releaseVersion }}" }'